create table sith_persons (
  id integer generated by default as identity primary key,
  name varchar2(200) not null unique,
  alive number(1,0) default 1 not null,
  constraint sith_persons_chk_alive_bol check ( alive in (1,0) )
);