create table sith_characters_t (
  id integer generated by default as identity primary key,
  alive number(1,0) default 1 not null,
  prename varchar2(100) not null,
  surname varchar2(100) not null,
  constraint sith_persons_chk_alive_bol check ( alive in (1,0) ),
  constraint sith_characters_uq_pre_surname unique (prename, surname)
);